# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermes < Formula
  desc "CLI tool to download Google Fonts"
  homepage "https://hermes.cadens.studio/"
  version "0.0.1-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-alpha/hermes_v0.0.1-alpha_macOS_arm64.tar.gz"
      sha256 "2733d29c646e7dd9627f8dbe39a75d074f1d18ac2ebb5213dbe19a4d70b49a44"

      def install
        bin.install "hermes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-alpha/hermes_v0.0.1-alpha_macOS_x86_64.tar.gz"
      sha256 "33452c1bc8fc3ac0fef26381847c37f1bb2cea3441321baf28ebe18daff979c8"

      def install
        bin.install "hermes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-alpha/hermes_v0.0.1-alpha_Linux_x86_64.tar.gz"
      sha256 "895187073d2d1e9f8bfb0b091e8050e15af1d818aa50bdffa2dc9a4aaa4b7e02"

      def install
        bin.install "hermes"
      end
    end
  end
end
