# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermes < Formula
  desc "CLI tool to download Google Fonts"
  homepage "https://hermes.cadens.studio/"
  version "0.0.1-beta"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-beta/hermes_v0.0.1-beta_macOS_arm64.tar.gz"
      sha256 "268243b4304151eda28dea2c1ac9fa7f0e1846b18486ea4eee28db7e0ba43860"

      def install
        bin.install "hermes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-beta/hermes_v0.0.1-beta_macOS_x86_64.tar.gz"
      sha256 "dc9442849d7a906d847eda4381ccb504fe881896886347e632928962ebcc54d4"

      def install
        bin.install "hermes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v0.0.1-beta/hermes_v0.0.1-beta_Linux_x86_64.tar.gz"
      sha256 "037c12c9cfaaa74abca3828e91a256b8f6e5329cb0f3fdd0e4f602290a06709d"

      def install
        bin.install "hermes"
      end
    end
  end
end
