# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermes < Formula
  desc "CLI tool to download Google Fonts"
  homepage "https://hermes.cadens.studio/"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cadensstudio/hermes/releases/download/v1.0.0/hermes_v1.0.0_macOS_arm64.tar.gz"
      sha256 "d988cd785d44c57954b8bf74162f91d4c91de6c21d877d47a557d82c4b48effb"

      def install
        bin.install "hermes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v1.0.0/hermes_v1.0.0_macOS_x86_64.tar.gz"
      sha256 "6937c67d38649085e7f928a3e3cd32b8f7505904f70233ee167413cedb1d3b86"

      def install
        bin.install "hermes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cadensstudio/hermes/releases/download/v1.0.0/hermes_v1.0.0_Linux_x86_64.tar.gz"
      sha256 "88401afca856412c00121b6a6b7c77877b20ca8f859eb848fbdd6d0c443287ae"

      def install
        bin.install "hermes"
      end
    end
  end
end
